"""
Simple rule-based detector that doesn't require external ML models.
Useful for demos/offline environments.
"""
import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'schemas')))
from models import DetectionRequest, DetectionResult
from detector import Detector, DetectorRegistry


AI_HINTS = [
    "as an ai language model",
    "i'm unable to",
    "cannot browse the internet",
    "large language model",
    "generated by ai",
]


class SimpleDetector(Detector):
    """A very lightweight heuristic-based detector."""

    def __init__(self, config: dict):
        super().__init__(config)
        self.threshold_len = int(config.get("threshold_len", 600))

    @property
    def model_name(self) -> str:
        return "simple-heuristic"

    async def detect(self, request: DetectionRequest) -> DetectionResult:
        text = request.text or ""
        lower = text.lower()

        # Heuristic signals
        has_ai_hint = any(h in lower for h in AI_HINTS)
        is_long = len(text) >= self.threshold_len

        if has_ai_hint:
            label = "AI-generated"
            confidence = 0.85
        elif is_long:
            label = "suspicious"
            confidence = 0.6
        else:
            label = "human-written"
            confidence = 0.7

        return DetectionResult(
            label=label,
            confidence=float(confidence),
            model_name=self.model_name,
            timestamp=datetime.utcnow(),
            metadata={
                "length": len(text),
                "ai_hints": [h for h in AI_HINTS if h in lower],
            },
        )


# Register this detector
DetectorRegistry.register("simple", SimpleDetector)
